// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4aYSUzGHv1DIhHwy6WbxJRxu-1SL5Ls4',
    appId: '1:275172499081:web:76949ee630e9aa0562f058',
    messagingSenderId: '275172499081',
    projectId: 'unityworkshop-project',
    authDomain: 'unityworkshop-project.firebaseapp.com',
    storageBucket: 'unityworkshop-project.firebasestorage.app',
    measurementId: 'G-VEVK7XMQQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xhz-hqLJ_q9oqa5X8v4qsU6pWOdgJ6g',
    appId: '1:275172499081:android:4cf94750afb872ee62f058',
    messagingSenderId: '275172499081',
    projectId: 'unityworkshop-project',
    storageBucket: 'unityworkshop-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5nnQA-ClHstJTf6JldoXUuoRNmcvaztY',
    appId: '1:275172499081:ios:b437c152556ff9c262f058',
    messagingSenderId: '275172499081',
    projectId: 'unityworkshop-project',
    storageBucket: 'unityworkshop-project.firebasestorage.app',
    iosBundleId: 'com.example.trainingHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5nnQA-ClHstJTf6JldoXUuoRNmcvaztY',
    appId: '1:275172499081:ios:b437c152556ff9c262f058',
    messagingSenderId: '275172499081',
    projectId: 'unityworkshop-project',
    storageBucket: 'unityworkshop-project.firebasestorage.app',
    iosBundleId: 'com.example.trainingHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4aYSUzGHv1DIhHwy6WbxJRxu-1SL5Ls4',
    appId: '1:275172499081:web:b4c2a5ccbf4074ad62f058',
    messagingSenderId: '275172499081',
    projectId: 'unityworkshop-project',
    authDomain: 'unityworkshop-project.firebaseapp.com',
    storageBucket: 'unityworkshop-project.firebasestorage.app',
    measurementId: 'G-6BBPX5QDVZ',
  );
}
